QuestionColor: 1
AnswerColor: 3
quizzMessage:
  StartMsg: "&eC'est parti pour le quizz!"
  StopMsg: "&eLe quizz est maintenant stoppe."
  BadAnswerMsg: "&4Mauvaise reponse!"
  GoodAnswerMsg: "&2Bonne reponse! Question suivante."
  AlReadyInQuizzMsg: "&4Vous etes deja dans un quizz!"
  NotInAQuizzMsg: "&4Vous n'etes pas dans un quizz!"
questions:
  q1:
    question: "Combien font 1+1?"
    rightAnswer: 1
    answers:
    - 2
    - 3
    - 1
  q2:
    question: "Le grief est-il autorise?"
    rightAnswer: 2
    answers:
    - Oui, sans moderation
    - Non
    - Non, mais des fois oui
Commands:
 - "say {player} a bien repondu au quizz!"
