quizzMessage:
  StartMsg: C'est parti pour le quizz!
  StopMsg: Le quizz est maintenant stoppe.
  BadAnswerMsg: Mauvaise reponse!
  GoodAnswerMsg: Bonne reponse! Question suivante.
  AlReadyInQuizzMsg: Vous etes deja dans un quizz!
  NotInAQuizzMsg: Vous n'etes pas dans un quizz!
questions:
  q1:
    question: Combien font 1+1?
    rightAnswer: 1
    answers:
      - 2
      - 3
      - 1
  q2:
    question: Le grief est-il autorisé?
    rightAnswer: 2
    answers:
      - Oui, sans modération
      - Non
      - Non, mais des fois oui
Commands:
  - say {player} a bien repondu au quizz!