name: PromoteQuizz
version: 0.2.5
description: a quizz plugin to promote players after correctly answered to all your questions
load: STARTUP
author: Olivier Cosquer
main: fr.oliviercosquer.PromoteQuizz.PromoteQuizz
commands:
  qcm:
    description: Toutes les commandes de qcm
    permissions: promoteQuizz.start
    usage: /<command> <commandaction>
