name: PromoteQuizz
version: 1.1.0
description: a quizz plugin to promote players after correctly answered to all your questions
load: STARTUP
author: Olivier Cosquer
depend: [Vault]
main: fr.oliviercosquer.PromoteQuizz.bukkit.PromoteQuizz
commands:
  qcm:
    description: Toutes les commandes de qcm
    permissions: promoteQuizz.qcm
    usage: /<command> <commandaction>
